default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: ""
  host: localhost
  
development:
  <<: *default
  database: blogs_db

test:
  <<: *default
  database: blogs_db

production:
  <<: *default
  database: blogs_db
